repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-format
        name: Ruff Format
        args: [--preview]
        files: ^src/

      - id: ruff
        name: Ruff Lint
        args: [--fix, --exit-non-zero-on-fix]
        files: ^src/