services:
  postgres-test:
    image: postgres:17.5-alpine3.22
    container_name: postgres_test
    restart: unless-stopped
    env_file:
      - .env.test
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - taskflow_net_test
    tmpfs:
      - /var/lib/postgresql/data

  redis-test:
    image: redis:8.0.3-alpine
    container_name: redis_test
    restart: unless-stopped
    env_file:
      - .env.test
    command: [ "redis-server", "--save", "" ]
    expose:
      - "${REDIS_PORT}"
    networks:
      - taskflow_net_test
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    tmpfs:
      - /data

  minio-test:
    build: ./minio
    container_name: minio_test
    expose:
      - "${MINIO_STORAGE_PORT}"
      - "${MINIO_WEB_PORT}"
    tmpfs:
      - /data
    env_file:
      - .env.test
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${MINIO_WEB_PORT}/minio/health/live" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - taskflow_net_test

  web-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: taskflow_web_test
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
      minio-test:
        condition: service_healthy
    env_file:
      - .env.test   # монтируем папку для отчёта
    environment:
      MIGRATION_INSIDE_DOCKER: 1
    volumes:
      - ./htmlcov:/fast_api/htmlcov
      - ./src:/fast_api/src
    networks:
      - taskflow_net_test
    command: ["sh", "-c", "alembic upgrade head && pytest -s"]

networks:
  taskflow_net_test:
    name: taskflow_net_test
    driver: bridge