"""Discord fields not null check

Revision ID: 0329af858727
Revises: 47f2b9f84c84
Create Date: 2025-08-03 20:57:00.084789

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0329af858727"
down_revision: Union[str, Sequence[str], None] = "47f2b9f84c84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_check_constraint(
        "ck_discord_fields_null_together",
        "user_profiles",
        "(discord_id IS NULL AND discord_username IS NULL) OR (discord_id IS NOT NULL AND discord_username IS NOT NULL)",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("user_profiles_discord_username_key"), "user_profiles", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_discord_fields_null_together", "user_profiles", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("user_profiles_discord_username_key"),
        "user_profiles",
        ["discord_username"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
