"""GIN-index for group and and max_members

Revision ID: 195b6598dc1a
Revises: 40ad1ded6b42
Create Date: 2025-08-22 21:16:01.453046

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "195b6598dc1a"
down_revision: Union[str, Sequence[str], None] = "40ad1ded6b42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column("max_members", sa.SMALLINT(), server_default=sa.text("100"), nullable=False),
    )
    op.create_index(
        "ix_groups_name_trgm",
        "groups",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_check_constraint("ck_group_max_members", "groups", "max_members BETWEEN 2 AND 100")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_groups_name_trgm",
        table_name="groups",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_column("groups", "max_members")
    op.drop_constraint("ck_group_max_members", "groups", type_="check")
    # ### end Alembic commands ###
