"""Made name group field Unique

Revision ID: 250d54da5bb3
Revises: 3028559c4074
Create Date: 2025-08-24 16:37:54.979242

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '250d54da5bb3'
down_revision: Union[str, Sequence[str], None] = '3028559c4074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    # ### end Alembic commands ###
