"""Added description field for group

Revision ID: 3028559c4074
Revises: 195b6598dc1a
Create Date: 2025-08-24 16:32:42.895233

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3028559c4074"
down_revision: Union[str, Sequence[str], None] = "195b6598dc1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups", sa.Column("description", sa.String(length=2000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "description")
    # ### end Alembic commands ###
