"""GIN-index and trgm for search

Revision ID: 40ad1ded6b42
Revises: 6d8ce3b30d45
Create Date: 2025-08-13 16:46:04.178792

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40ad1ded6b42"
down_revision: Union[str, Sequence[str], None] = "6d8ce3b30d45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_profiles_name"), table_name="user_profiles")
    op.create_index(
        "idx_users_username_trgm",
        "user_profiles",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_users_username_trgm",
        table_name="user_profiles",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_user_profiles_name"), "user_profiles", ["name"], unique=False
    )
    # ### end Alembic commands ###
