"""Fix Foreign Key

Revision ID: 47f2b9f84c84
Revises: 23262b57f5a1
Create Date: 2025-08-03 18:55:30.612370

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47f2b9f84c84"
down_revision: Union[str, Sequence[str], None] = "23262b57f5a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("user_profiles_id_fkey"), "user_profiles", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "user_profiles", "users", ["id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_profiles", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_profiles_id_fkey"), "user_profiles", "users", ["id"], ["id"]
    )
    # ### end Alembic commands ###
