"""Info about user avatar

Revision ID: 79220f938232
Revises: 8fa60a75fefa
Create Date: 2025-08-11 21:58:29.118904

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79220f938232"
down_revision: Union[str, Sequence[str], None] = "8fa60a75fefa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("has_avatar", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "has_avatar")
    # ### end Alembic commands ###
