"""Added indexes for group_id, user_id for groups

Revision ID: b00ad9f1644b
Revises: bdafbc742825
Create Date: 2025-09-01 19:04:42.845723

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b00ad9f1644b'
down_revision: Union[str, Sequence[str], None] = 'bdafbc742825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_gup_group_group_members', 'group_members', ['group_id'], unique=True)
    op.create_index('ix_gup_user_group_group_members', 'group_members', ['user_id', 'group_id'], unique=True)
    op.create_index('ix_gup_user_group_group_user_permissions', 'group_user_permissions', ['user_id', 'group_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gup_user_group_group_user_permissions', table_name='group_user_permissions')
    op.drop_index('ix_gup_user_group_group_members', table_name='group_members')
    op.drop_index('ix_gup_group_group_members', table_name='group_members')
    # ### end Alembic commands ###
