"""Made user search by login except name

Revision ID: bdafbc742825
Revises: 250d54da5bb3
Create Date: 2025-08-24 16:52:32.019069

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bdafbc742825'
down_revision: Union[str, Sequence[str], None] = '250d54da5bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_users_username_trgm'), table_name='user_profiles', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index('idx_users_login_trgm', 'users', ['login'], unique=False, postgresql_using='gin', postgresql_ops={'login': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_login_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'login': 'gin_trgm_ops'})
    op.create_index(op.f('idx_users_username_trgm'), 'user_profiles', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
