"""cascade deletes if user leave from group

Revision ID: d4420a170b69
Revises: b00ad9f1644b
Create Date: 2025-09-01 19:31:58.329284

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4420a170b69"
down_revision: Union[str, Sequence[str], None] = "b00ad9f1644b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "group_invitations",
        "group_members",
        ["group_id", "inviter_id"],
        ["group_id", "user_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "group_user_permissions",
        "group_members",
        ["group_id", "user_id"],
        ["group_id", "user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group_user_permissions", type_="foreignkey")
    op.drop_constraint(None, "group_invitations", type_="foreignkey")
    # ### end Alembic commands ###
