"""Added privacy fields

Revision ID: efd13d1707a0
Revises: 0329af858727
Create Date: 2025-08-05 12:52:28.217746

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efd13d1707a0"
down_revision: Union[str, Sequence[str], None] = "0329af858727"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "groups",
        "name",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("groups_creator_id_fkey"), "groups", type_="foreignkey")
    op.create_foreign_key(
        None, "groups", "users", ["creator_id"], ["id"], ondelete="RESTRICT"
    )
    op.add_column(
        "user_profiles",
        sa.Column("show_discord", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "user_profiles",
        sa.Column(
            "show_telegram", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "user_profiles",
        sa.Column("show_email", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "show_email")
    op.drop_column("user_profiles", "show_telegram")
    op.drop_column("user_profiles", "show_discord")
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.create_foreign_key(
        op.f("groups_creator_id_fkey"),
        "groups",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "groups",
        "name",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
